### PR TITLE
fix: Not updating raw github imports; Update dependencies

### PR DESCRIPTION
**Pull request by drashbot**
This pull request was auto-generated by GitHub Actions.

### CODE REVIEW

**Comment by ebebbington** [comment]
Dmm itself (when it made this pr) should have updated the wocket import in the up to date deps (as dmm now supports. github urls), which makes me think this feature is broken

**Comment by ebebbington** [comment]
fixed the issue, dmm. wasn't updating the dep, even though it said it did

**Review by saragee3 — APPROVED** [review]
changes make sense but what happened? just catching up.

**Comment by ebebbington** [comment]
The bumper overwrote the changes I made, so I had to pull the branch locally, fixed merge conflicts then push back up to add my changes :p

**Pull request merged**
