### PR TITLE
Add linter to master.yml

### LINKED ISSUE #27: Make `deno lint` Pass
## Summary

What: If you run `deno lint`, we will most likely have a whole bunch of errors. This issue to fix these errors by correctly formatting code, and abiding by Deno's standards 

Why: It would be good to make sure the code follows either: Deno's best practices, coding standards, or general best practices. It's a Deno project so it makes sense to utilise their tools on making the code Deno-like

## Acceptance Criteria

- `deno lint` is added to the `master.yml` CI, as a new block (similar to how we use `deno fmt --check` on some repositories)
- `deno lint` produces no errors

## Resources

[Deno Lint Documentation](https://github.com/denoland/deno_lint)

### PR DESCRIPTION
**Pull request by saragee3**
Fixes #27 

**Description**

* `deno lint` passes.
* add `deno lint --unstable` to master.yml

### CODE REVIEW

**Comment by ebebbington** [comment]
Nice one! 😄 Maybe we could merge it into the update tests PR? as that's the pr that updates deno (which is why the tests are failing)

**Comment by ebebbington** [comment]
Actually might need to merge master into this branch to update all the tests (or merge to master anyway and see what happens 😆 )

**Comment by Guergeiro** [comment]
I think we should wait until the `--unstable` flag is removed. Being `--unstable` means it's rules might change in the future.

**Comment by crookse** [comment]
yea let's wait until the `--unstable` flag is removed.

**Comment by crookse** [comment]
blocked reason: deno lint is still behind the unstable flag

**Comment by crookse** [comment]
closing. no need for this yet. deno lint is still very unstable

**Pull request closed without merging**
