### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by drashbot**
This was auto-generated by GitHub Actions.

### CODE REVIEW

**Comment by ebebbington** [comment]
Similar to how rhum and drash are now with the update script, dmm has one too. The difference being, there is more to update, one notable problem was trying to update the std versions inside the README, so i made a `.README.md` as a 'placeholder', so we can easily replace `{{ latestStdVersion}}`. The reason for this, was because say we have the following:
```
fs was updated from 0.53.0 to 0.68.0
``` 
To not break anything, we'd have to have regex that was like `.replace(/<module> was updated from <version> to <new_version>/`

**Comment by ebebbington** [comment]
Ready for review, i just had to add the running of the script to the bumper (i must have forgotten), and the last commit was me running the script so everything should be good

**Comment by Guergeiro** [comment]
@ebebbington it was force-pushed by @drashbot. Can you push again and I'll review it?

**Comment by ebebbington** [comment]
> @ebebbington it was force-pushed by @drashbot. Can you push again and I'll review it?

@Guergeiro good for review now

**Review by Guergeiro — APPROVED** [review]
Seems good to me. Only hard review I did was the script and should be okay!

**Pull request merged**
